<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf97c278be8477dd85a4800f75930b1db
{
    public static $prefixLengthsPsr4 = array (
        'I' => 
        array (
            'Iron\\Services\\Translation\\' => 26,
            'Iron\\Services\\App\\' => 18,
            'Iron\\Services\\' => 14,
            'Iron\\Service\\Session\\' => 21,
            'Iron\\Config\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Iron\\Services\\Translation\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/app/services/translation',
        ),
        'Iron\\Services\\App\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/app/services/app',
        ),
        'Iron\\Services\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/app/services',
        ),
        'Iron\\Service\\Session\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/app/services/session',
        ),
        'Iron\\Config\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/app/config',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf97c278be8477dd85a4800f75930b1db::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf97c278be8477dd85a4800f75930b1db::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
