<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Iron\\Services\\Translation\\' => array($baseDir . '/app/services/translation'),
    'Iron\\Services\\App\\' => array($baseDir . '/app/services/app'),
    'Iron\\Services\\' => array($baseDir . '/app/services'),
    'Iron\\Config\\' => array($baseDir . '/app/config'),
);
