<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitec5f59ad781e379bf1ee00a472b4886e
{
    public static $prefixLengthsPsr4 = array (
        'I' => 
        array (
            'Iron\\Services\\Translation\\' => 26,
            'Iron\\Services\\App\\' => 18,
            'Iron\\Services\\' => 14,
            'Iron\\Config\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Iron\\Services\\Translation\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/app/services/translation',
        ),
        'Iron\\Services\\App\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/app/services/app',
        ),
        'Iron\\Services\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/app/services',
        ),
        'Iron\\Config\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/app/config',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitec5f59ad781e379bf1ee00a472b4886e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitec5f59ad781e379bf1ee00a472b4886e::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
